services:

  nginx:
#    image: nginx:latest
    build: ./nginx
    ports:
      - "80:80"
    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - private-network
    depends_on:
      - fastapi
      - vue

  postgres:
    image: postgres:16-alpine 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - .env
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks: 
      - private-network
    restart: always
    
  fastapi:
    build: ./fastapi
    env_file:
      - .env
 #   ports:
 #     - "8000:8000"
    networks:
      - private-network
    depends_on:
      - postgres
    restart: always
  
  vue:
    build: ./vue-project
#    ports:
#      - "5174:5173"
    networks:
      - private-network
    depends_on:
      - fastapi
    restart: always
networks:
  private-network:
